FROM  italiangrid/pkg.base:centos5

ENV BUILD_NAME storm-gridhttps-server
ENV BUILD_REPO git://github.com/italiangrid/storm-gridhttps-server
ENV BUILD_TAG develop
ENV PKG_REPO git://github.com/italiangrid/pkg.storm.git
ENV PKG_TAG master
ENV PKG_SPEC_FILE storm-gridhttps-server/rpm/storm-gridhttps-server/storm-gridhttps-server.spec

USER build
