sudo: required
services:
- docker
dist: trusty
env:
  matrix:
    - PLATFORM=centos6
    - PLATFORM=centos7
  global:
  - PKG_TAG=$TRAVIS_BRANCH
  - PACKAGES_VOLUME="pkg-vol-$TRAVIS_BUILD_ID"
  - STAGE_AREA_VOLUME="sa-vol-$TRAVIS_BUILD_ID"
  - PKG_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - PKG_NEXUS_HOST=https://repo.cloud.cnaf.infn.it
  - PKG_UPLOAD_RPMS=1
  - INCLUDE_BUILD_NUMBER=1
  - secure: gzGdrp9TprEWBS6+h2w6NHLkjfM9z7Hmsmn7aSGftPviLpKgPF5Fu0YFKcyUp0XUwRgYUYg0SKMlLo18mMfgEXpuZWcTJV+nMa4G8Rdhtak4VDOAet1Kv/Xn7IcmTfjFzHdKgEVPFM/Hgk9haeIYvKi71WS1CcsfwtwZSOLgJRpq1+iQZArbgNTNMOwQ8h1REyiwx33/OD7eiG5tgzqut3o0Cw00Ri58bcztD8lGLlwECZixhxhvRCIC1u8/buT4kTUWpHyJVTQMJnPtHNKs5kK8qFfoKFJlEAnGnlD075UXqlloSO69iylowXevXK4WwYVoCceM1fM2kVbyY5Lo+G2c8sP/XfuEpFvxWiRpQ3XFv5lOZDnaQ90XDBiPQZmfAvSqLadaGRg4kIB5HQxWCRgCVEFrGOlPlWQVhMp+CRobNd4SWqbFkOQ3YHvorVajsjDTM204UEy9vAx+8+M33AJtpDAmyKP+eArWOuQYuWQRj8AHoDJZk3zbmo+DYu7DQulNJmc/ALTO5ULH5vRbwo9dv4CZ0zuyLMQY+71rLm52ElT0/L1ILRtDUy3izqQv1CXcBrSQnUlegsRC1IP7DpRipIpDPXOQVVwFfUwchx2m7lN+0fhqmKrQen7ed6BdFUwrtxpUQPvkqkH4qMWLLhN/u46LjcRRLdT3Mtwuc3Q=
  - secure: bRkV0U673tpu8Z9i7ffZAUSH/Hes0GVUrMLujgOHNOVXKgPuMyMiA7jyC8TD7ravEidbuiqSBdpmAolIYlxZtLFUYZM1hgYhdzaUXBZ6gJQHT/4cfmWahoDE37W4FXMNAUP4FwJ9+uDy9pL0sw838hsO9TMe+jTy9wvKlIpqoyG3FbAycBt72nKCxUi0dVXID8T+tLH5fc0KdoZrCHs1CfCI4Xa0IUgKlnoDunYKBYKlph0ZxCCa5dN3q3hBg48a+NA/2+eCqhLe36eY0K1qusGZbzR5Ez5SuKYdPYdPL4LaiaW/Ail5ttYMkHSCZ6JKQ9UXAbnr3CV+rRJWM1OS8XcRQMY48qH0icjgSsyN9gZ75lY/w9eLNSV7xWP8Ay4rBV8BKZF4mwgnDICRAfLLB/XkwFqQSSKLKiO730YRG0BEKSn4kGbkGe2Y2CHwzwjzgaPFkCsLyT7UrQGlynNNlH9prVkeCN6nHMKDtK4odLJDqZWfT9IuIRBWWPnxfpsOkD9mzfub/CGyc1jJ6Y55Vkv04lOQ1w8RmCdnSefYgSKLVFvuBgAu747ugyAmIOCQPjePd4/1hiuIgn/3G0mgpCxGo1fN3N62Re6TZCUERT06u8/SbOfO8qZ6/URuK4QpO5tvik6ahxIwCZvhZbEncMXDNq9vAN/eLXgLODNBR9g=
before_script:
  - git clone https://baltig.infn.it/mw-devel/helper-scripts.git /tmp/helper-scripts
  - export PATH=$PATH:/tmp/helper-scripts/scripts/
script:
  - bash travis/build.sh
notifications:
  slack:
    rooms:
      secure: HccKBHYVrpEQdmDzn17MjdaDmLABdMjOm8kZtgJyOA3eHp7Cqsmuvch2HmX81ovbqadMFPJnsRMYok7feKyuc/hppdhiXBvq6CfFYDxjGwA529izSlCncavcVPVIy8fBRTV/ZDdPbI/j2YfTwN4wiixGzqRU/62ba69Zuw87Cmyx/1qMGzu9suyCc+zPvZ+CzAX1qoH+cVEMLjBmJYoY5DdUhQWoXCH9fHEy1KcvAVi/Dcbuj0IauSBTG4wT+c3Uyb7ERk8KiN521uPz9r8w0umYw3YY05sfQbZyoEHZinY9hiEj1HeYYSC2ixGWLlCTIRAd5ckMrtZzyzhRL/oBWdCj26jv+b9RqGiWxNojCYwWc7xV/1IIMY00gOdBsvUiQ1RtKQdTOJKFOGSE4IvVr6eAbXJsmdQXg2X4iIH1BErEfjYFmq19RajQx40e6OIoCNtkKpx7a41UHIA1+LYwqAgRXbuVcploW6cviM4wG7qACjyglMUy67K6278gWcHRGs1g6Ti9LISuC0MYxOXLBBwfoYvg+etoe2D6cJkbLZvWOsRjwczbALXEH1ZUXvtoXlrPAPVhhU4wFo05oPzhqauaQUb7H6C3uApD4/Ut4eTbc1HlJr4B+eF7l8+SiIpV/y607tjqdaur+Dgn5VOjT4o51CYCTS7F+2CGSK9diVU=
