FROM  italiangrid/pkg.base:centos7

ENV BUILD_NAME storm-webdav
ENV BUILD_REPO git://github.com/italiangrid/storm-webdav
ENV BUILD_TAG develop
ENV PKG_REPO git://github.com/italiangrid/pkg.storm.git
ENV PKG_TAG master
ENV PKG_SPEC_FILE storm-webdav/rpm/storm-webdav/storm-webdav.spec
ENV TARBALL_VERSION_REQUIRED 1

USER build
