FROM  italiangrid/pkg.base:centos5

RUN yum -y install pkgconfig \
  globus-gssapi-gsi-devel \
  globus-gss-assist-devel \
  gsoap-devel \
  CGSI-gSOAP-devel \
  voms

ENV BUILD_NAME storm-srm-client
ENV BUILD_REPO git://github.com/italiangrid/storm-client
ENV BUILD_TAG develop
ENV PKG_REPO git://github.com/italiangrid/pkg.storm.git
ENV PKG_TAG master
ENV PKG_SPEC_FILE storm-srm-client/rpm/storm-client/storm-srm-client.spec

USER build
