FROM  italiangrid/pkg.base:centos6

RUN yum -y install pkgconfig \
  swig \
  libacl-devel \
  gpfs.base \
  lcmaps-without-gsi-devel \
  lcmaps-interface

ENV BUILD_NAME storm-native-libs
ENV BUILD_REPO git://github.com/italiangrid/storm-native-libs
ENV BUILD_TAG develop
ENV PKG_REPO git://github.com/italiangrid/pkg.storm.git
ENV PKG_TAG master
ENV PKG_SPEC_FILE storm-native-libs/rpm/storm-native-libs/storm-native-libs.spec

USER build
