FROM  italiangrid/pkg.base:centos5

RUN yum -y install pkgconfig 

ENV BUILD_NAME yaim-storm
ENV BUILD_REPO git://github.com/italiangrid/yaim-storm
ENV BUILD_TAG develop
ENV PKG_REPO git://github.com/italiangrid/pkg.storm.git
ENV PKG_TAG master
ENV PKG_SPEC_FILE yaim-storm/rpm/yaim-storm/yaim-storm.spec

USER build
